export const favoriteItemSearchableFields = [
  'propertyName',
  'squareFeet',
  'bathrooms',
  'bedrooms',
  'features',
  'rentType',
  'propertyAbout',
  'address.governorate',
  'address.area',
  'address.block',
  'address.street',
  'address.house',
  'address.floor',
  'address.apartment',
];

export const favoriteItemFilterableFields = [
  '_id',
  'propertyName',
  'squareFeet',
  'bathrooms',
  'bedrooms',
  'features',
  'rentType',
  'ype',
  'propertyAbout',
  'address.governorate',
  'address.area',
  'address.block',
  'address.street',
  'address.house',
  'address.floor',
  'address.apartment',
  'user',
  'searchTerm',
];
