export const favoriteItemSearchableFields = ['propertyName', 'propertyAbout'];
export const favoriteItemFilterableFields = [
  'propertyName',
  'squareFeet',
  'bathrooms',
  'bedrooms',
  'features',
  'rentType',
  'ype',
  // 'perNightPrice',
  // 'perMonthPrice',
  'propertyAbout',
  'address.governorate',
  'address.area',
  'address.block',
  'address.street',
  'address.house',
  'address.floor',
  'address.apartment',
  'user',
  'searchTerm',
];
